
language: php
#php: 5.5

# Deployment information
deploy:
  provider: pages # Tell Travis we want to deploy to Github Pages
  skip-cleanup: true


  repo: KazMalhotra/kazmalhotra.github.io #https://kazmal.tech
 
